---
- hosts: nodes
  tasks:
  - include_tasks: _infra_setup.yml
    tags: [ 'always' ]

# init local first
- hosts: controllers[0]
  become: false
  roles:
    - { role: infra-defaults }
  tasks:
    - name: "hostname | Set hostname now & permanently"
      hostname:
        name: "{{ inventory_hostname }}"
    - name: import bootstrap/tasks/yum_repository.yml
      import_role:
        name: bootstrap
        tasks_from: yum_repository
    - name: import bootstrap/tasks/kernel_version.yml
      import_role:
        name: bootstrap
        tasks_from: kernel_version

    - name: import bootstrap/tasks/nvidia_drivers.yml
      import_role:
        name: bootstrap
        tasks_from: nvidia_drivers
      when: is_kube_gpu

#    - name: import bootstrap/tasks/atlas_drivers.yml
#      import_role:
#        name: bootstrap
#        tasks_from: atlas_drivers
#      when: is_kube_npu

    - name: import bootstrap/tasks/iptables.yml
      import_role:
        name: bootstrap
        tasks_from: iptables
  tags: ['init']

# prepare
- hosts: nodes
  roles:
    - { role: bootstrap }
    - { role: cis, tags: ['cis'] }
  tags: ['prepare']

# kubernetes
- hosts: nodes
  tasks:
    - name: set skip_downloads false
      set_fact:
         skip_downloads: false

- hosts: k8s-cluster:etcd
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: kubespray-defaults}
    - { role: kubernetes/preinstall, tags: preinstall }
    - { role: "container-engine", tags: "container-engine", when: deploy_container_engine|default(true) }
    - { role: download, tags: download, when: "not skip_downloads" }
  environment: "{{ proxy_env }}"

- hosts: nodes
  tasks:
    - name: set skip_downloads false
      set_fact:
         skip_downloads: true

- name: import k8s cluster.yml
  import_playbook: cluster.yml

- hosts: kube-master[0]
  roles:
    - { role: kubespray-defaults, tags: [ 'always' ] }
    - { role: lib_yaml_editor, tags: [ 'always' ] }
    - { role: k8s, tags: ['kubernetes'] }